# Database config
spring.application.name=SnippetHub
spring.datasource.url=jdbc:postgresql://localhost:5432/localdb
spring.datasource.username=hydrogen
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update